### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [Co-d-er/CreditCardValidator#4]
Pass `"50000000000006114"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number does not pass Luhn check)
Actual result: "Maestro"

**Comment by Co-d-er** [comment]
I don't understand this issue. In this article https://en.wikipedia.org/wiki/Bank_card_number is writen that maestro can have 16 up to 19 digits. So the result of my function is correct as number length equils 17.

**Comment by intrueder** [comment]
Did you read explanation in parenthesis? I don't believe that any issuer is allowed to give his clients credit cards with invalid card numbers.
One more time, card number is INVALID. Expected result for this case is `Unknown` vendor.

**Comment by Co-d-er** [comment]
I've fixed. Please, check.
